.travis.yml
tox.ini

Leveraging tox-travis for running environments per-python version.
python 3.6 was arbitrarily chosen to run `flake8` and `docs` environments.

feat(CI): Configure travis

---

nixnet/dummy.py
nixnet/nx.py
nixnet/nxdb.py

This attempts to capture all of the functions within the NI-XNET C API.
This will serve as the basis for designing an OOP API in #9.
Closes #4

feat(API): Create c-like API skeleton

---

nixnet/_cfuncs.py
nixnet/_ctypedefs.py
nixnet/_lib.py

Fixed #10
Task list
Guideline checklist
A mockable wrapper around nixnet.dll for the OOP API to call into

RFC: feat: Low-level (ctypes) wrapper around nixnet.dll

---

nixnet/_cprops.py
nixnet/_props.py
nixnet/constants.py
nixnet/nx.py
nixnet/types.py
nixnet_examples/can_frame_stream_input.py

Ports an NI-XNET example over along with proposing enough of an API design for that example.
Some areas of risk
- One `Session` type or one per-mode?
- Which module parts of the API go into?
- Impracticalities of implementing LV-like high level API on top of the C
API (like READ_ALL_AVAILABLE).
This serves as a stepping stone towards fleshing out the API (see #22 / #23).
Closes #27

feat(API): Specced out for can_frame_stream_input

---

nixnet/nx.py

Adds all remaining (non-sub) properties to Session.
The properties convert to/from enums where applicable except for `intf_flex_ray` properties.  I skipped those for now.  I'll create an issue once this is submitted for us to handle those.  I noticed #44 while doing this process.
Ref properties are not converted at this time.  I have an action item to create an issue for us to resolve those.
For now, write-only properties were left as functions.  I have an action item to create an issue for us to resolve those.
This PR does not try to get fancy with sub-objects like the DAQmx API.  That will come in a separate PR where we can play with what it is that is appropriate for XNET.
This is a step towards resolving #23.
None

feat(API): Add all non-sub properties to Session

---

nixnet/db/__init__.py
nixnet/db/cluster.py
nixnet/db/database.py
nixnet/db/ecu.py
nixnet/db/frame.py
nixnet/db/linsched.py
nixnet/db/linsched_entry.py
nixnet/db/pdu.py
nixnet/db/signal.py
nixnet/db/subframe.py
nixnet/nxdb.py

This adds properties to `Database` and all sub-objects.
In addition, database `save` and cluster `merge` are included.  Further
database organization is being deferred.
This is a step to #9.
None

feat(API): Add `Database` objects

---

nixnet_examples/can_frame_queued_io.py

Adds CAN Frame Queued I/O Example
This is a stepping stone to fleshing out the API.
None

Adding Frame Queued IO Example

---

nixnet/_frames.py
nixnet/_funcs.py
nixnet/nx.py
nixnet_examples/can_frame_queued_io.py
nixnet_examples/can_frame_stream_io.py
tests/test_examples.py

Fixes most bugs in the frame examples.  There is still some frame parsing as part of `read_can_frame` that isn't working.
Getting everything closer to working
Created and run tests with a mock library.  This doesn't return any data though.

fix(ctypes): Get examples mostly-running

---

nixnet/_funcs.py

Gets frame stream running
Hand testing

fix(ctypes): `can_frame_stream_io` now works

---

nixnet/__init__.py
nixnet/_session/frames.py
nixnet/_session/signals.py
nixnet/_utils.py
nixnet/session.py
nixnet_examples/can_frame_queued_io.py
nixnet_examples/can_frame_stream_io.py
nixnet_examples/can_signal_single_point_io.py
tests/test_examples.py

This is a part of #23 where we are trying to get the API stable-ish.
Benefits
- Guide the user to relevant API functionality rather than burying it in
docs or waiting until runtime errors
- Tailored `Session.__init__` for the mode, like LabVIEW
- Static design (read/write don't dynamically adapt based on the mode),
allowing for improved static analysis.
Downsides
- Reads and writes are common operations but buried one level deeper.
- But similar to DAQmx's `stream` object but more context aware (but
DAQmx has "simple read/write" flavors)
- `Session.frames` and `Session.signals` already existed so it can
logically make sense to put these operation on those objects.
- The reads/writes would already have "signals" and "frames" in there
name, so the overall length isn't any longer.
- Less …

feat(API): Split `Session` into classes per-mode

---

Jenkinsfile.txt
tox.ini

Added initial Jenkinsfile to root and updated tox.ini to exclude from Travis CI
Adds a generic Jenkinsfile to root so that the Jenkins server can begin testing. Modifies the Tox.ini to exclude the Jenkinsfile.
Part of the CI server setup.
None.

Add Jenkinsfile to root

---

nixnet/_session/base.py
nixnet/_session/frames.py
nixnet/_session/signals.py
nixnet/session.py

Adds docstrings for the Session class. The documentation is based off of the C API documentation fouind here: http://zone.ni.com/reference/en-XX/help/372841N-01/TOC63.htm
Provides meaningful documentation for the Session API. We will use this to generate html version of the docs as well.
None

Adding docstrings for SessionBase class, mode specific sesssion classes, frame and signal read and write functions

---

README.rst
docs/README.rst
tox.ini

The `README.rst` now has a strong emphasis on the essential information to
get someone going.  In addition, there is an API status section.
In addition, links were updated to readthedocs.

docs: Update landing page

---

nixnet/_session/frames.py

docs(API): Session Frame properties

---

nixnet/_enums.py
tests/test_system.py

Fixes #104
BREAKING CHANGE: Renamed Err.PORT_LE_DS_BUSY to Err.PORT_LEDS_BUSY

fix(API): Correct spelling of Err.PORT_LEDS_BUSY

---

.gitignore
.travis.yml
tox-integration.ini
tox.ini

tests: Report code coverage

---

nixnet/_enums.py
nixnet/_funcs.py
nixnet/_session/base.py
nixnet/_utils.py
nixnet/types.py
tests/test_frames.py

There are two controversial parts of this
- If the interface isn't communication, time_start and time_communicating
throw an error rather than return 0.
- Each state property will treat `fault` like any other return code,
raising an exception or warning, when these properties are accessed
Standard checklist

feat(state): Report general and CAN session state

---

tox-integration.ini

So the hacks pile up.  We have a separate file to avoid running the tests
on TravisCI.  We need all the main environments listed in this separate
file so we can do syntax checks on it (because of how tox-travis works).
The problem is that then caused our tests to be run under all of those
environments on Jenkins but the dependencies weren't installed.
So limiting the test run to the test environment seems to make everything
happy.

fix(CI): Only run tests under test environments

---

Jenkinsfile

Since we don't have a Jenkins badge on the front page, it might be
difficult to track when builds have failed besides our immediate PR, like
with master.  So emailing relevant people.

feat(CI): Email reports

---

nixnet/_session/base.py
nixnet/_session/frames.py
nixnet/_session/intf.py
nixnet/_session/signals.py
nixnet/errors.py
nixnet/session.py
nixnet/types.py
tests/test_errors.py

- Fix property documentation that was in function form
- Add parameter types
- Rename setter parameters to be more context aware
- Default `set_j1939_addr_filter` to reflect `reset` in documentation
- Allow `set_j1939_addr_filter` to also take an `int` to simplify
documentation.
- Corrected Warning member variables to not mention errors
BREAKING CHANGE
`Frame` set function parameter names have changed.  If keyword arguments
are used, they will need to be updated.
`XnetWarning`'s `error_code` and `error_type` have been renamed to
`warning_code` and `warning_type`.

docs: Clean up documentation

---

README.rst
nixnet/_py2.py
nixnet/_session/frames.py
nixnet/types.py
nixnet_examples/can_frame_queued_io.py
nixnet_examples/can_frame_stream_io.py
tests/test_frames.py

nixnet will now automatically adapt Frame `read`/`write` calls based on
the data being transfered rather than requiring per-frame-type read/write
calls (like `read_can`/`write_can`).
This will help when adding special frame types.  Without this change, they
would have been interpreted as `CanFrame` which would provide weird
results unless someone thought to check `frame.type` and then they'd have
to go through hoops to get it into the correct frame object to interpret
it correctly.
This lowers the visibility of `read_raw`/`write_raw` in the API which
should only be used for some specific advanced cases anyways (arbitrary
data logging).
`read_can` has been replaced by `read`.  If the session reads non-CAN
frames (see special frame types), then those will be included in …

feat(API): Simplify read/write calls

---

nixnet/_session/intf.py
nixnet/types.py
nixnet_examples/can_frame_queued_io.py
nixnet_examples/can_frame_stream_io.py
tests/test_frames.py

`out_strm_list_by_id` might contain either LIN or CAN frames IDs without a
way to distinguish them so we can't completely abstract it like we did for
IDs in the actual Frames.  Instead the parsing logic from `CanFrame` was
extracted and abstracted so it can be reused with this property
(`CanIdentifier`).
Fixes #115
BREAKING CHANGE: `CanFrame` now accepts a single `CanIdentifier` rather
than an `(int, bool)`.  An `int` can still be passed in as a short-form
and will be interpreted as a non-extended id.

feat(API): Provide can ID parser for `out_strm_list_by_id`

---

nixnet/_ctypedefs.py
tests/test_frames.py
tests/test_session_intf.py

tests: Expand coverage

---

tests/test_session.py
tests/test_session_intf.py

tests(Session): Expand coverage

---

tests/test_session.py

tests(Session): Add failure tests to terminal connections

---

nixnet/types.py

fix(API): Frame ID validation to support 11 bit (not 10)

---

docs/base.rst
docs/collection.rst
docs/constants.rst
docs/enums.rst
docs/errors.rst
docs/frames.rst
docs/index.rst
docs/intf.rst
docs/j1939.rst
docs/session.rst
docs/signals.rst
docs/types.rst
nixnet/_session/frames.py
nixnet/_session/intf.py
nixnet/session.py

This will better match how the API is used.

docs: Re-organize documentation tree

---

nixnet/_session/frames.py
nixnet/session.py

Some read/write parameter names have changed, breaking uses of keyword
parameters.

docs: Improve consistency on naming and types

---

docs/convert.rst
docs/index.rst
nixnet/_funcs.py
nixnet/convert.py
nixnet/session.py
nixnet_examples/can_signal_conversion.py
tests/test_convert.py
tests/test_examples.py

	feat(API): Signal/Frame conversion mode

---

nixnet/types.py

fix(tests): CanBusErrorFrame repr was untested

---

nixnet/_cfuncs.py

While nixnet doesn't have callbacks to exacerbatge the problem, still
wanting to protect things.  nidaqmx went with a per-function lock.  That
is probably overkill for our needs so going with a global library loading
lock.
Not introducing double-check locking into the picture because the
conditional initialization is just an optimization.  nixnet should not
have any problems if two threads make it into the initialization check,
especially considering every call did initalization in the past.
Fixes #146

fix: Improve thread safety

---

nixnet/_session/frames.py
nixnet/_session/signals.py
tests/test_signals.py

Signal cleanup

---

nixnet/session.py
nixnet/types.py
nixnet_examples/can_frame_queued_io.py
nixnet_examples/can_frame_stream_io.py
nixnet_examples/can_signal_conversion.py
nixnet_examples/can_signal_single_point_io.py
tests/test_examples.py
tests/test_frames.py

This mostly focuses on fixing #170. 
- Improve the frame repr
- Print payloads in examples
Some other minor fixes are done while at it.

fix(examples): Improve reporting of frames (+ other stuff)

---

nixnet/_session/signals.py

This is only relevant to SignalsWaveform and will be re-added by #161.
Fixes #121.
BREAKING CHANGE: `session.signals` no longer has a `resamp_rate` property.
This never worked anyways so it shouldn't impact anyone.

fix(API): Remove irrelevant resamp_rate property

---

nixnet/_session/collection.py

Because of what these return when iterated, they act more like a
`Sequence` rather than `Mapping`, so we're changing them to actually map
that.
Fixes #173
BREAKING CHANGE: `session.frames` and `session.signals` no longer have
`keys`, `items`, and `values`.  We do not expect this to impact anyone.

fix(API): signals and frames semantics

---

Jenkinsfile
nixnet/_enums.py
nixnet/_funcs.py
nixnet/_session/base.py
nixnet/_session/intf.py
nixnet_examples/lin_frame_stream_io.py
tests/conftest.py
tests/test_examples.py
tests/test_frames.py
tests/test_session.py
tests/test_session_intf.py
tests/test_signals.py
tests/test_system.py
tox-integration.ini

Added read and write frame for LIN. Added LIN frame object.
Stepping stone for LIN support.
Doc tests only

feat(API): Support lin_sched

---

nixnet/_enums.py
nixnet/_funcs.py
nixnet/_props.py
nixnet/_session/base.py
nixnet/_session/intf.py
nixnet/_utils.py
nixnet/types.py
tests/test_frames.py
tests/test_session.py
tests/test_session_intf.py
tests/test_signals.py
tests/test_system.py

TODO
See #91 
Some functions/properties/parameter names have changed.  Technically we
didn't support these before but someone might have started to use them
anyways.
- session.intf.set_lin_sleep(value) -> session.intf.set_lin_sleep(state)
- session.intf.lin_diag_p_2min -> session.intf.lin_diag_p2min
- session.intf.lin_diag_s_tmin -> lin_diag_stmin
- session.intf.lino_str_slv_rsp_lst_by_nad -> session.intf.lin_ostr_slv_rsp_lst_by_nad
Checklist

feat(API): Support LIN interface properties

---

MANIFEST.in
docs/api_reference.rst
docs/api_reference/databases.rst
docs/api_reference/system.rst
docs/examples.rst
docs/examples/programmatic_databases.rst
nixnet/_funcs.py
nixnet/nxdb.py
nixnet/system/databases.py
nixnet/system/system.py
nixnet_examples/databases/custom_database.dbc
nixnet_examples/programmatic_database_usage.py
tests/test_examples.py
tests/test_system.py

Adds partial database API support.
Enhances the API with programmatic database functionality.  This fixed #77.
The example runs as expected. Integration and unit tests run as expected.
Goals
- Be pythonic (including using ABCs that make sense
- Keep things simple to the user; minimizing opening handles unless needed and make it clear when its done
**DatabaseAlias Mapping**
(current design)
`System.databases` is a custom `Mapping` object with Alias objects that store the results.  These objects could also have an "open database" call.
iter, keys, values, items, len, getitem, delitem all work as expected.
setitem could be implemented.  There are a couple of annoyances
- A `DatabaseAlias` object would need to be created by the user and passed in.
- It could only succeed for database formats …

	 feat(API): Adding partial database API support

---

docs/api_reference.rst
docs/api_reference/system.rst
docs/api_reference/system/device.rst
docs/api_reference/system/interface.rst
docs/api_reference/system/system.rst
nixnet/_enums.py
nixnet/system/_device.py
nixnet/system/_interface.py
nixnet/system/system.py
nixnet/types.py
tests/test_system.py

docs(API): Document `System`

---

Jenkinsfile

It turns out Jenkins doesn't make environment variables available to
`bat`.  We are probably doing something wrong but we need the tests
running now.
So in the mean time, we're manually invoking specific
environments to get integration coverage back up.

fix(tests): Re-enable CI integration tests 

---

.gitignore
CONTRIBUTING.rst
docs/examples.rst
docs/examples/database_creation.rst
nixnet/_cprops.py
nixnet/_enums.py
nixnet/db/_ecu.py
nixnet/db/_linsched_entry.py
nixnet/db/database.py
nixnet_examples/can_dynamic_database_creation.py
nixnet_examples/lin_dynamic_database_creation.py
nixnet_examples/lin_frame_stream_io.py
tests/test_examples.py

Add CAN and LIN database creation examples

---

.gitignore
MANIFEST.in
docs/api_reference.rst
docs/api_reference/database.rst
docs/api_reference/database/cluster.rst
docs/api_reference/database/dbc_attributes.rst
docs/api_reference/database/ecu.rst
docs/api_reference/database/frame.rst
docs/api_reference/database/signal.rst
nixnet/_funcs.py
nixnet/database/_cluster.py
nixnet/database/_dbc_attributes.py
nixnet/database/_ecu.py
nixnet/database/_frame.py
nixnet/database/_signal.py
tests/databases/attributes.dbc
tests/test_dbc_attributes.py

Add get_dbc_attribute method for cluster,
frame, ECU, and signal objects.
Add tests and a DBC containing attributes.

feat(DB): Add methods to get_dbc_attribute

---

docs/api_reference/database.rst
docs/api_reference/database/dbc_signal_value_table.rst
nixnet/database/_dbc_signal_value_table.py
nixnet/database/_signal.py
tests/databases/attributes.dbc
tests/test_dbc_attributes.py
tests/test_dbc_signal_value_table.py

Expose Signal property named dbc_signal_value_table
that returns a mapping to a DBC value table.
Add related docs and tests.

feat(API): Add DBC signal value table 

---

LICENSE
docs/api_reference/database.rst
docs/api_reference/database/collection.rst
docs/api_reference/database/database.rst
docs/conf.py
docs/examples/dynamic_database_creation.rst
nixnet/_session/base.py
nixnet/database/_collection.py
nixnet/database/database.py
nixnet_examples/can_dynamic_database_creation.py
nixnet_examples/lin_dynamic_database_creation.py

Document database/database.py and database/_collection.py.

docs(DB): Add a few docs for database.

---

nixnet/_session/base.py
nixnet/convert.py
nixnet/database/database.py
nixnet/system/system.py

`__exit__` parameter 'type' shadows a built-in name.
I like the descriptive naming chosen [here](http://docs.quantifiedcode.com/python-anti-patterns/correctness/exit_must_accept_three_arguments.html).

chore(API): Improve parameter names on __exit__.

---

nixnet/database/_cluster.py

feat(DB): Add method to export clusters to a database file.

---

nixnet/database/_dbc_signal_value_table.py
tests/test_dbc_signal_value_table.py

Fixes #229
DBC signal value is now int instead of string.

fix(API): DBC signal values are integers.

---

nixnet/system/_databases.py

feat(API): Make add_alias's default_baud_rate optional.

---

nixnet/_errors.py
nixnet/_funcs.py
nixnet/_utils.py
nixnet/database/_cluster.py
nixnet/database/_ecu.py
nixnet/database/_frame.py
nixnet/database/_lin_sched.py
nixnet/database/_lin_sched_entry.py
nixnet/database/_pdu.py
nixnet/database/_signal.py
nixnet/database/_subframe.py
nixnet/database/database.py
tests/test_session.py

Before, we just returned the status code.
However, the user previously had no way to get the text for the status code.
Now, return the status code and text in a tuple.

refactor(API): have config_status return status code and text.

---

nixnet/database/_frame.py
nixnet/database/_pdu.py
nixnet/types.py

This PR implements issue #53  by removing the pdu_* properties with a single pdu properties. The old interface required parallel lists, this implementation uses a single list of namedtuples.
#53 
I tested this with my CAN device by creating a PDU that met the requirements of [PDUs Required?](http://zone.ni.com/reference/en-XX/help/372841L-01/nixnet/propertyclusterpdusrequired/). I verified I could configure and take measurements without any warnings. If I didn't conform to PDUs required, I got either a warning or error depending on the case.

`Frame.pdu_*` properties should be considered for a tuple

---

docs/api_reference/database/lin_sched.rst
docs/api_reference/database/lin_sched_entry.rst
nixnet/_session/intf.py
nixnet/database/__init__.py
nixnet/database/_cluster.py
nixnet/database/_collection.py
nixnet/database/_database_object.py
nixnet/database/_ecu.py
nixnet/database/_find_object.py
nixnet/database/_frame.py
nixnet/database/_lin_sched.py
nixnet/database/_lin_sched_entry.py
nixnet/database/_pdu.py
nixnet/database/_signal.py
nixnet/database/_subframe.py
nixnet/database/database.py

Fixes #239
The following parent database objects now have a find method:
- database
- cluster
- lin schedule
- pdu
- frame
- subframe
All database object are now subclasses of
DatabaseObject, which is used as an interface.
Database objects are now exposed through the
nixnet.database namespace, and their constructors
now take kwargs to signal to users that these
objects should not be instantiated by users.
I tested on the shipping example database "NIXNET_example"
to ensure I can indeed find children and grandchildren,
and that sane errors are thrown when the object name
not found or the object class is wrong.
Unit tests will be added in #238.

feat(API): Add descendant find for parent db objects.

---

nixnet_examples/can_frame_queued_io.py
nixnet_examples/can_frame_stream_io.py
nixnet_examples/lin_frame_stream_io.py
nixnet_examples/programmatic_database_usage.py

~~- []New tests have been created for any new features or regression tests for bugfixes.~~
in python 2.7.latest, payloads were getting printed in non-ascii characters/symbols
Fixing payload print issue for python27 and improving it for python34.
Making sent and receive print lines consistent so we can compare them
easily.

fix(examples): payload print issue

---

nixnet/types.py

Fixes #266
CanIdentifier's _FRAME_ID_MASK should allow 11-bit IDs.

fix(API): CAN frame ID's are 11 bits

---

nixnet/database/_collection.py
tests/test_database_collection.py
tests/test_errors.py

Fixes #264
- Add an integration test for DbCollection class.
- Fix test_driver_call to be less dependent on driver string.

fix(API): Fix bug in DbCollection.__repr__

---

nixnet_examples/programmatic_database_usage.py

While this example functions on Windows, the backslash in the DBC file path prevents it from functioning properly on Linux.
I replaced the backslash with proper path construction that will work for all platforms.
Replaced backslash to ensure that the example can run on Linux
To allow this example to run on Linux.
Manual testing of the example to ensure that it forms the path properly.

Replaced backslash to ensure that the example can run on Linux

---

nixnet/_session/collection.py
nixnet/_utils.py
nixnet/database/_collection.py
nixnet/database/_dbc_attributes.py
nixnet/database/_dbc_signal_value_table.py
nixnet/system/_collection.py
nixnet/system/_databases.py

I replaced deprecated use cases of "collections" with up to date "collections.abc" for python 3.3+ leaving backwards compatibility. This makes it possible to use nixnet with python 3.10 where those deprecated use cases were no longer supported.
Support for 3.10 enables enjoying bug-fixes like:
[bpo-41299](https://bugs.python.org/issue?@action=redirect&bpo=41299): Fix 16ms jitter when using timeouts in [threading](https://docs.python.org/3/library/threading.html#module-threading), such as with [threading.Lock.acquire()](https://docs.python.org/3/library/threading.html#threading.Lock.acquire) or [threading.Condition.wait()](https://docs.python.org/3/library/threading.html#threading.Condition.wait).
I successfully used the changes to test a CAN bus with python 3.10.

Fix python 3.10 errors (deprecated collections)

---

docs/api_reference/types.rst
docs/conf.py

~- [ ] New tests have been created for any new features or regression tests for bugfixes.~
~- [ ] `tox` successfully runs, including unit tests and style checks (see [CONTRIBUTING.md](https://github.com/ni/nixnet-python/blob/main/CONTRIBUTING.rst)).~
This PR is to fix the docs-related errors that will arise when the Sphinx dependency is upgraded to v7.1.2 for newer Python versions.
This PR is part of a series of PRs to prepare for supporting newer Python versions.
Locally run `tox` successfully with Python 3.7.9 (there are some existing issues with running tox with Python 3.4 or older and Python 3.8 or newer (requires upgraded dependencies), except flake8 which fails due to some existing issues which will be fixed in a subsequent PR.

Fix `tox -e docs` errors with Sphinx 7.1.2

---

nixnet/_frames.py
nixnet/_session/collection.py
nixnet/_utils.py
nixnet/system/_collection.py
nixnet_examples/programmatic_database_usage.py
requirements_test.in
requirements_test.txt
tests/test_dbc_attributes.py
tests/test_dbc_signal_value_table.py
tests/test_errors.py
tests/test_examples.py
tests/test_frames.py
tests/test_session.py

~- [ ] New tests have been created for any new features or regression tests for bugfixes.~
This PR is to fix the existing flake8 warnings that are generated from running `tox -e flake8`.
This PR fixes the existing flake8 warnings so that `tox` can be successfully run.
Successfully run `tox` with Python 3.7.9 (there are some existing issues with running tox with Python 3.4 or older and Python 3.8 or newer (requires upgraded dependencies).

Fix flake8 warnings

---

tests/conftest.py
tox-integration.ini
tox.ini

~- [ ] New tests have been created for any new features or regression tests for bugfixes.~
This PR is to fix the pytest-related warnings that will arise when the Pytest dependency is upgraded to 8.3.5 for newer Python versions.
It fixes the error in the form of:
```
PytestUnknownMarkWarning: Unknown pytest.mark.integration - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
@pytest.mark.integration
```
This PR is part of a series of PRs to prepare for supporting newer Python versions.
- Locally run `tox` successfully with Python 3.7.9 (there are some existing issues with running tox with Python 3.4 or older and Python 3.8 or newer (requires upgraded dependencies)
- Locally run `tox -e test` with …

Fix Pytest warnings with `pytest 8.3.5`

---

nixnet/_session/collection.py
tox.ini

~- [ ] New tests have been created for any new features or regression tests for bugfixes.~
This PR is to fix the flake8 W503 (Line break occurred before a binary operator) error that will be thrown when the `flake8` dependency is upgraded to `v7.1.2` to support newer Python versions.
`W503` conflicts with `W504` (Line break occurred after a binary operator), hence we'll need to disable one of them. This PR adds `W503` to the flake8 ignore list in tox.ini.
This PR also removes `H903: Windows style line endings not allowed in code` from the existing flake8 ignore list since [this error code does not seem to be valid](https://www.flake8rules.com/).
This PR is part of a series of PRs to prepare for supporting newer Python versions.
- Locally run `tox` successfully with Python 3.7.9
- Locally …

Fix flake8 W503 error and remove H903 from flake8 ignore list
