- .travis.yml
This is an attempt to fix the Travis builds for Python <3.5
> fix(CI): Upgrade to required pip version

- nixnet/_cfuncs.py
- nixnet/_ctypedefs.py
> Adding bool and null terminated strings to ctypes work

- nixnet/_cfuncs.py
- nixnet/_funcs.py
- nixnet/nx.py
- nixnet/nxdb.py
Connects most API functions to driver entry points
Stepping stone towards #11 and #24.
None
> Implement most API function calls

- nixnet/_cfuncs.py
- nixnet/_funcs.py
Change parts of the API to use bools rather than ints.
This is a more correct python representation.
None
> fix(API): Use bool rather than int

- nixnet/_cprops.py
This is the last bit of glue to connect object properties to the NI-XNET C API.
This is a stepping stone towards #24 
None
> feat(ctypes): Implement wrappers around get/set property

- nixnet/_cprops.py
- nixnet/_ctypedefs.py
- nixnet/_funcs.py
- nixnet/nx.py
Connects the public `read_signal_single_point` with the ctypes implementation.
This is a step towards implementing #24.
None
> feat(API): Implement `read_signal_single_point`

- nixnet/nx.py
- nixnet_examples/can_signal_single_point_io.py
TODO: Check the above boxes with an 'x' to indicate what steps you have taken in preparing this Pull Request.
Adds CAN Signal Single Point IO example and enhances the OOP API layer as needed.
This is a stepping stone to fleshing out the API.
None
> CAN Signal Single Point IO example

- nixnet/db/database.py
- nixnet/nx.py
- nixnet/system/system.py
Fixed #61
Clean up error messages so the real error is more obvious
None
> fix(API): Fix `__del__` to not error

- nixnet/db/database.py
- nixnet/nx.py
- nixnet/system/system.py
Make session types follow context manager protocol
Allow applications to function
> fix(API): Correct context managers.

- nixnet/_cprops.py
- nixnet/_funcs.py
- nixnet/_props.py
- nixnet/nx.py
Removes a lot of roadblocks to getting a functioning example
None
> fix(ctypes): Correcting lots of little mistakes

- nixnet/_funcs.py
Fixes calls into driver that use out-params and strings
Another step in getting examples running
None
> fix(ctypes): Out-param and strings

- nixnet/_cprops.py
- nixnet/_ctypedefs.py
- nixnet/_funcs.py
- nixnet_examples/can_signal_single_point_io.py
Minor API changes for getting the CAN signal single point example working.
Gets one of the examples working.
Successfully ran the example on a test machine with driver installed.
> Minor API changes to get the signal single point example working

- nixnet/_funcs.py
- Fix calls to `check_for_error`
- Fix array in-params
None
> fix(ctypes): Expanding fixes from examples

- nixnet/_ctypedefs.py
- nixnet/_frames.py
- nixnet/_funcs.py
- nixnet/constants.py
- nixnet/nx.py
- nixnet/types.py
- nixnet_examples/can_frame_queued_io.py
- nixnet_examples/can_frame_stream_io.py
- tests/test_frames.py
Examples should almost work
Doc tests only
> feat(API) Implement reading and writing CAN frames

- nixnet_examples/can_frame_queued_io.py
- nixnet_examples/can_signal_single_point_io.py
Ensures all examples work
Hand tested
> fix(docs): Get all examples working

- .travis.yml
- MANIFEST.in
- README.rst
- nixnet/_ctypedefs.py
- setup.py
- tox.ini
Language wise: pypy, pypy3
Test wise: manifest, setuptools
> feat(CI): Increase CI coverage

- MANIFEST.in
- tox.ini
Includes LICENSE in sdist
I'm guessing this is more correct
tox / hand checked the sdist.
> fix(pkg): Include license in sdist

- python_packages.txt
> chore: Remove dead file

- nixnet/nx.py
- nixnet_examples/can_frame_queued_io.py
- nixnet_examples/can_frame_stream_io.py
- nixnet_examples/can_signal_single_point_io.py
- Fixes references to properties after the last API change
- Cleaned up examples
- Added default values to `Session`
None
> fix(examples): Clean up examples

- nixnet_examples/can_frame_stream_io.py
> fix(examples): Baud rate not set

- README.rst
> docs: Fixing link

- nixnet/_session/collection.py
- nixnet/_session/intf.py
Makes `Frames` and `Signals` act more like a list and dict.
This better implements python's protocol for sequences and mappings.
> feat(API): Extend dict/list-like functionality

- README.rst
- docs/base.rst
- docs/collection.rst
- docs/enums.rst
- docs/errors.rst
- docs/frames.rst
- docs/index.rst
- docs/intf.rst
- docs/j1939.rst
- docs/session.rst
- docs/signals.rst
- docs/types.rst
- nixnet/_enums.py
- nixnet/_session/base.py
- nixnet/_session/frames.py
- nixnet/_session/signals.py
- nixnet/errors.py
- nixnet/session.py
- nixnet/types.py
-Adds reStructuredText files for Sphinx documentation generation support. 
-Switches to using `:any:` for cross-referencing as Sphinx generates warnings for bad targets (helps catch broken links).
-Fixes broken references for functions/classes
-Other minor changes/fixes for Sphinx to work
Note that doc references for enums, constants and properties are still broken, will address this in a separate PR.
Adds documentation generation support for the 0.1 release.
Ran Sphinx and reviewed the generated documentation.
> Adding RST files + Documentation cleanup

- nixnet/system/_device.py
- nixnet/system/_interface.py
- tests/test_frames.py
- tests/test_system.py
> System tests

- nixnet/_cfuncs.py
- nixnet/_ctypedefs.py
- nixnet/_funcs.py
> feat(ctypes): Improve type safety

- nixnet/__init__.py
- nixnet/_cfuncs.py
- nixnet/_cprops.py
- nixnet/_ctypedefs.py
- nixnet/_errors.py
- nixnet/_funcs.py
- nixnet/_lib.py
- nixnet/_props.py
- nixnet/_session/__init__.py
- nixnet/errors.py
- setup.py
- tests/test_errors.py
- tests/test_examples.py
- tests/test_frames.py
- tests/test_signals.py
- tests/test_system.py
- tox-integration.ini
- tox.ini
Enable type analysis
Improve correctness
integration tests were re-run
> feat(CI): Enable mypy

- nixnet/_funcs.py
- nixnet/_props.py
- nixnet/errors.py
- nixnet/system/_device.py
- nixnet/system/_interface.py
- nixnet/system/system.py
- nixnet/types.py
- tests/test_errors.py
> feat(API): Annotate API for mypy

- nixnet/_enums.py
- nixnet/_session/base.py
Adding docstrings for session base properties.
Stepping stone to writing all documentation.
ran 'make html' to generate html documentation. reviewed the generated documentation.
> chore(API): Adding session base prop docstrings

- nixnet/_enums.py
- nixnet/_session/intf.py
- nixnet/db/_cluster.py
> docs(API): Session interface properties

- nixnet/_enums.py
- nixnet/_props.py
- nixnet/_session/base.py
- nixnet/_session/intf.py
- nixnet/db/_cluster.py
- nixnet/db/_frame.py
> fix(API): Correct minor naming issues

- nixnet/_session/base.py
- nixnet/_session/frames.py
- nixnet/_session/signals.py
- tests/test_frames.py
Moves properties to relevant sub classes. 
Prevents the user from using the attribute with unsupported session classes (that could otherwise lead to errors or do nothing and leave dead code behind). 
None
> feat(API): Moving properties to relevant classes

- nixnet/_cprops.py
- nixnet/_props.py
> feat(ctypes): Annotate prop wrappers

- Jenkinsfile
Established environment variables in the Jenkinsfile to specify hardware for CI testing.
To enable CI testing with hardware.
Verified Jenkins executes test script on my dev fork.
> Adding environment variables to Jenkinsfile

- nixnet/_funcs.py
- nixnet/_session/base.py
- nixnet/_session/collection.py
- nixnet/_session/frames.py
- nixnet/_session/signals.py
- nixnet/session.py
> feat(API): Annotate Session types

- Jenkinsfile
- tox-integration.ini
- tox.ini
Capture junit logs
Better error reporting in the Jenkins CI (integration testing)
Verified junit files are written out successfully.  Did not test the Jenkins side of things.
> feat(CI): Capture test results

- tests/test_session_intf.py
> Fix broken integration test

- tests/test_examples.py
> tests: Increase example coverage

- .gitignore
- Jenkinsfile
- tox-integration.ini
- tox.ini
> feat(CI): Integrate coverage with Jenkins

- nixnet/_props.py
- nixnet/_session/frames.py
> fix(API): Remove unused property

- nixnet/_session/base.py
- nixnet/_session/collection.py
- nixnet/_session/intf.py
- nixnet/db/_cluster.py
- nixnet/db/_ecu.py
- nixnet/db/_frame.py
- nixnet/db/_linsched.py
- nixnet/db/_linsched_entry.py
- nixnet/db/_pdu.py
- nixnet/db/_signal.py
- nixnet/db/_subframe.py
- nixnet/db/database.py
- nixnet/system/_device.py
- nixnet/system/_interface.py
- nixnet/system/system.py
- nixnet/types.py
> fix: Comparison operator behavior

- nixnet_examples/can_frame_queued_io.py
- nixnet_examples/can_frame_stream_io.py
- nixnet_examples/can_signal_single_point_io.py
> fix(examples): Correct report formatting

- nixnet/types.py
Implement convenience objects for [special frames](http://zone.ni.com/reference/en-XX/help/372841N-01/nixnet/specialframes/).
> feat: Special frame support

- tests/test_frames.py
> tests(Frame): Increase coverage

- nixnet/_session/frames.py
- nixnet/types.py
- tests/test_frames.py
Adds/ updates LinFrame
Adds LinFrame support.
Doc tests
> feat(API): Implement Linframe type

- nixnet/types.py
This should also get them showing up in the documentation.
> fix(API): Include special frames in wildcard import

- CONTRIBUTING.rst
- tests/conftest.py
- tests/test_frames.py
- tests/test_session.py
- tests/test_session_intf.py
- tests/test_signals.py
- tests/test_system.py
- tox-integration.ini
> feat(tests): Skip tests when hardware is `None`

- docs/examples.rst
- docs/examples/can_lin_diff.rst
- docs/examples/queued_io.rst
- docs/examples/single_point_io.rst
- docs/examples/stream_io.rst
Add diff and new headings for example documentation. 
Add LIN documentation.
> docs(examples) Restructure documentation to add LIN

- README.rst
- docs/api_reference.rst
> fix(docs): Project status in README

- README.rst
> fix(docs): Get README working with github's parser

- nixnet/_funcs.py
- nixnet/system/_databases.py
- nixnet/system/system.py
> feat(API): Annotate types for db alias

- nixnet/_session/base.py
- nixnet/convert.py
- nixnet/system/_databases.py
- nixnet/system/_device.py
- nixnet/system/_interface.py
- nixnet/system/system.py
- tests/test_system.py
> test(API): Increase Alias coverage 

- nixnet/db/_frame.py
- nixnet/db/_subframe.py
> fix(API): Correct signal parenting in DB

- nixnet_examples/programmatic_database_usage.py
> fix(examples): Fix relative database path in database example

- nixnet/_session/base.py
- nixnet/_session/collection.py
- nixnet/_session/intf.py
- nixnet/_session/j1939.py
- nixnet/convert.py
- nixnet/database/_cluster.py
- nixnet/database/_collection.py
- nixnet/database/_ecu.py
- nixnet/database/_frame.py
- nixnet/database/_linsched.py
- nixnet/database/_linsched_entry.py
- nixnet/database/_pdu.py
- nixnet/database/_signal.py
- nixnet/database/_subframe.py
- nixnet/database/database.py
- nixnet/system/_collection.py
- nixnet/system/_databases.py
- nixnet/system/_device.py
- nixnet/system/_interface.py
- nixnet/system/system.py
- nixnet/types.py
> chore(API): increase uniformity of dunders

- tests/test_database_cluster.py
- tests/test_database_database.py
- tests/test_database_ecu.py
- tests/test_database_frame.py
- tests/test_database_lin_sched.py
- tests/test_database_lin_sched_entry.py
- tests/test_database_pdu.py
- tests/test_database_signal.py
- tests/test_database_subframe.py
>  tests(DB) Add tests for database namespace.

- .travis.yml
> fix(test): Update pypy versions for Travis CI

- nixnet/convert.py
- tests/test_convert.py
- [ X] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/nixnet-python/blob/master/CONTRIBUTING.rst).
- [ X] New tests have been created for any new features or regression tests for bugfixes.
Fix for #275 
Bugfix of infinite loop.
Test added for previously failing case.
> Convert bug
